name: CI

on:
  pull_request:
  push:
    branches:
    - d/main
  schedule:
  - cron: '0 1 * * *'

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: clippy
    - name: Run tests
      run: cargo test --all-targets
    - name: Check Clippy
      run: cargo clippy --all-targets -- -D warnings
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        # rustfmt is often missing on nightly. Since there's little benefit to
        # using the nightly version, use the more reliable stable build instead.
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Check formatting
      run: |
        cargo fmt -- --check
